os:
    - linux
language: node_js
node_js:
    - "8.9.1"
cache:
  directories:
#    - $HOME/.yarn-cache
#    - node_modules
before_install:
 #  - npm -g i yo bower gulp-cli
    # Install Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn -v
    - yarn global add yo
install:
    - yarn install
    - yarn link
    - yarn run coveralls